server:
  port: 8081
  max-http-request-header-size: 16KB

tam:
  security:
    rate-limit:
      capacity: 100
      refill-period-seconds: 60

spring:
  application:
    name: event-tracker
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  servlet:
    multipart:
      max-request-size: 16KB
      max-file-size: 16KB

logging:
  level:
    com.theanimalmap: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: event-tracker