server:
  port: 8081
  max-http-request-header-size: 16KB

spring:
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  servlet:
    multipart:
      max-request-size: 16KB
      max-file-size: 16KB

logging:
  level:
    com.theanimalmap: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always